name: Daily Weather Log

on:
  schedule:
    - cron: "0 * * * *"  # runs every hour
  workflow_dispatch:

jobs:
  update-weather:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install requests python-dotenv matplotlib pandas

      - name: Run weather script
        env:
          OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
        run: python weather.py

      - name: Generate chart
        run: python chart.py

      - name: Commit and push updated log and chart
        run: |
          git config user.name "Aravind R S"
          git config user.email "aravind54500@gmail.com"
          git add weather_log.csv temperature_chart.png
          git commit -m "Update weather log and chart" || echo "No changes to commit"
          git push